apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: billing-service-nyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: billing-service-nyc
    app.kubernetes.io/part-of: nyc-transit
  name: billing-service-nyc
  namespace: shbose
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: billing-service-nyc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: billing-service-nyc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:shbose-billing-service-nyc
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 190m
            memory: 160Mi
status: {}
