apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shbose
bases:
- components/1-java-quarkus/base
- components/basic-go/base
- components/billing-service-nyc/base
- components/map-service/base
resources:
- common-storage-pvc.yaml
