apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-java-quarkus
    app.kubernetes.io/part-of: nyc-transit
  name: 1-java-quarkus 
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: 1-java-quarkus
    weight: 100 
