apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: x1-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x1-java-quarkus
    app.kubernetes.io/part-of: nyc-transit
  name: x1-java-quarkus 
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: x1-java-quarkus
status:
  loadBalancer: {}
